"""update table to include longitude and latitude

Revision ID: 392110904a45
Revises: fd2825b09648
Create Date: 2024-12-25 13:24:34.280731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392110904a45'
down_revision: Union[str, None] = 'fd2825b09648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('emergencies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('emergency_locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('emergency_locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('responders', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('responders', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responders', 'longitude')
    op.drop_column('responders', 'latitude')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'latitude')
    op.drop_column('emergency_locations', 'longitude')
    op.drop_column('emergency_locations', 'latitude')
    op.drop_column('emergencies', 'longitude')
    op.drop_column('emergencies', 'latitude')
    # ### end Alembic commands ###
