"""add foreign key to profile model

Revision ID: 3b43dbb7b41c
Revises: 7002778f96d8
Create Date: 2024-11-05 19:46:52.265759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b43dbb7b41c'
down_revision: Union[str, None] = '7002778f96d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencies', sa.Column('attachments', sa.String(), nullable=True))
    op.alter_column('emergencies', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('profile', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'profile', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    op.alter_column('emergencies', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('emergencies', 'attachments')
    # ### end Alembic commands ###
