"""empty message

Revision ID: 6a6beb06743e
Revises: 3b43dbb7b41c
Create Date: 2024-11-07 12:01:11.491223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6beb06743e'
down_revision: Union[str, None] = '3b43dbb7b41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responder_emergencies', sa.Column('final_report_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'responder_emergencies', 'final_reports', ['final_report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responder_emergencies', type_='foreignkey')
    op.drop_column('responder_emergencies', 'final_report_id')
    # ### end Alembic commands ###
