"""add analytics and report table

Revision ID: 7002778f96d8
Revises: 4f24c2572b1c
Create Date: 2024-10-25 11:13:36.023454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7002778f96d8'
down_revision: Union[str, None] = '4f24c2572b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_reports',
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('emergency_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergency_id'], ['emergencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_reports_id'), 'final_reports', ['id'], unique=False)
    op.create_table('data_analytics',
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('avg_response_time', sa.Float(), nullable=False),
    sa.Column('most_common_emergency_type', sa.String(), nullable=False),
    sa.Column('total_emergencies', sa.Integer(), nullable=False),
    sa.Column('total_resources_used', sa.Integer(), nullable=False),
    sa.Column('most_used_resource_type', sa.String(), nullable=False),
    sa.Column('most_active_responder_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['most_active_responder_id'], ['responders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_analytics_id'), 'data_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_analytics_id'), table_name='data_analytics')
    op.drop_table('data_analytics')
    op.drop_index(op.f('ix_final_reports_id'), table_name='final_reports')
    op.drop_table('final_reports')
    # ### end Alembic commands ###
