"""add locations table

Revision ID: 7e00e08f1ef3
Revises: 6a6beb06743e
Create Date: 2024-12-25 02:37:28.441867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7e00e08f1ef3'
down_revision: Union[str, None] = '6a6beb06743e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

conn = op.get_bind()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    result = conn.execute(sa.text("SELECT to_regclass('public.idx_locations_geo_location')"))
    index_exists = result.scalar()

    if not index_exists:
        # Create the index only if it doesn't exist
        op.create_index('idx_locations_geo_location', 'locations', ['geo_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index('idx_locations_geo_location', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    # ### end Alembic commands ###
