"""add location string to emergency table

Revision ID: a2127ada0e3d
Revises: 392110904a45
Create Date: 2024-12-26 14:18:52.877822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2127ada0e3d'
down_revision: Union[str, None] = '392110904a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencies', sa.Column('location_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencies', 'location_str')
    # ### end Alembic commands ###
