"""add emergency location table

Revision ID: fd2825b09648
Revises: 7e00e08f1ef3
Create Date: 2024-12-25 11:20:11.521806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


conn = op.get_bind()

# revision identifiers, used by Alembic.
revision: str = 'fd2825b09648'
down_revision: Union[str, None] = '7e00e08f1ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('geo_location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    result = conn.execute(sa.text("SELECT to_regclass('public.idx_emergency_locations_geo_location')"))
    index_exists = result.scalar()

    if not index_exists:
        # Create the index only if it doesn't exist
        op.create_index('idx_emergency_locations_geo_location', 'emergency_locations', ['geo_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_emergency_locations_id'), 'emergency_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_locations_id'), table_name='emergency_locations')
    op.drop_index('idx_emergency_locations_geo_location', table_name='emergency_locations', postgresql_using='gist')
    op.drop_table('emergency_locations')
    # ### end Alembic commands ###
